# Generated by Django 4.2 on 2023-04-17 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='submitted',
        ),
    ]
